### ISSUE TITLE
"Next episode" not working

### ISSUE THREAD

**Issue by Drivermate** [Ceereals/BingeFlix#2]
The extension no longer skips to the next episode

## Expected Behavior
At the end of each episode the script *should* automatically skip to the next episode

## Current Behavior
Simply does not skip anymore, which kind of goes against the functionality of the program itself. Other functionalities are working fine (Skip intro/skip summary)
This started to happen since the last update, which introduced the "skip summary" feature.

## Possible Solution
Going back to the last version as soon as possible, then finding a way to introduce the skip summary feature, since "next episode" is way more important than "skip summary"

## Steps to Reproduce (for bugs)

1. Open browser
2. Open neflix
3. Watch an episode until the end
4. Be sad because it doesn't go to the next episode

## Context
I was trying to automatically skip the episode

## Your Environment
* Version used: Last one
* Browser Name and version: Firefox
* Operating System and version (desktop or mobile): Windows 10

**Comment by Ceereals** [comment]
Your issuse is now solved!

**Comment by Drivermate** [comment]
Understandable have a nice day
