### ISSUE TITLE
[ISSUE] Extension doesn't work

### ISSUE THREAD

**Issue by rayman89** [Ceereals/BingeFlix#3]
I'm on firefox 56.0 x64 release on windows 7 x64 the addon does not skip intro nor next episode.

**Comment by Ceereals** [comment]
Which version are you using?

**Comment by rayman89** [comment]
Latest version of the addon

**Comment by Ceereals** [comment]
If possible, can you press F12 while you're in www.netflix.com and go to debugging under moz-extension and take a screenshot?

**Comment by rayman89** [comment]
like this? 
![image](https://user-images.githubusercontent.com/5449042/34424235-afcb6e9a-ebe7-11e7-92e6-330febbae79d.png)

**Comment by Ceereals** [comment]
Exactly, how you can see there's a file called `skipper.js` so the script should run while you're watching to netflix. I don't know if you know something about html, but I need to know what the "skip intro" key classes are, you should use the inspector for target the button and then see the classes (if you want you can take another screenshot). I am grateful for the help you are giving me to improve the extension.

**Comment by rayman89** [comment]
![image](https://user-images.githubusercontent.com/5449042/34426666-c362ba0a-ebfe-11e7-8394-ac1d55ce488f.png)

**Comment by Ceereals** [comment]
The script is very simple, I was only checking for some change from my Netflix version, but it’s the same and the script is injected. Did you unflag the popup for enabling the script?

**Comment by rayman89** [comment]
I don't understand what you mean by "Did you unflag the popup for enabling the script?" The addon was enabled when I looked at the element inspector.

**Comment by Ceereals** [comment]
The extension has a popup in which there is a checkbox that enables or disables the operation of the extension. Have you tried to use that function?

**Comment by rayman89** [comment]
I never saw that popup I tried disabling all the other addons in case they were interfering but it didn't appear anyway. Wouldn't it be more convenient though if that option was on a on off button on the url bar?

**Comment by Ceereals** [comment]
It would be convenient but I have to work on it. So I think the problem is the version of firefox, have you tried to update firefox?

**Comment by Ceereals** [comment]
Could you give me the complete error from the console including the lines where the error occurred? if you want you could use the debugging of the script in the debugging section and put the stop on the error line and execute the code, line by line.

**Comment by rayman89** [comment]
I tested on the newer version and It's the same. The first time I load the tab it does skip the intro but if I go back to test again reload the tab or try on the next episode it does nothing and it also does not skip to the next episode:

BTW I have this kind of next episode thing

![image](https://user-images.githubusercontent.com/5449042/34441278-3c612d2a-ec80-11e7-816d-29a2171b94aa.png)

**Comment by Ceereals** [comment]
Ok, we're near the answer. Go to netflix's settings and disable the native "watch next episode" toggle. I recommend even if you had to refresh the page to open a new tab and close the previous one. I also found your problem on the refresh but I still could not find the solution for that.

**Comment by Drivermate** [comment]
Ricca ti droghi cose sta roba

Il 29/dic/2017 04:13 PM, "rayman89" <notifications@github.com> ha scritto:

**Comment by rayman89** [comment]
seems to be working now thank you
