### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by rayman89** [Ceereals/BingeFlix#4]
Seems that netflix changed something and it does not skip intro or next episode anymore for me.  I'm using firefox 56 x64 on win 7 x64

**Comment by Ceereals** [comment]
I need the same screenshot like the last time.

**Comment by rayman89** [comment]
SKIP

![imagen](https://user-images.githubusercontent.com/5449042/34957594-d91184dc-f9f3-11e7-81a9-9df3433fe093.png)

Next EP

![imagen](https://user-images.githubusercontent.com/5449042/34957653-20d65400-f9f4-11e7-8cfa-8942aa708a3a.png)

**Comment by Ceereals** [comment]
You have the auto-skip function of netflix, try to disable it.

**Comment by rayman89** [comment]
Thanks sorry to have bothered you again auto-skip got enabled somehow and disabling it made it work again.

**Comment by Ceereals** [comment]
No problem man, i'm here for any issues!

**Comment by Ceereals** [comment]
Now you can see the popup?

**Comment by rayman89** [comment]
This? 
![imagen](https://user-images.githubusercontent.com/5449042/34958425-80b328be-f9f7-11e7-85ba-478443b9763f.png)

**Comment by Ceereals** [comment]
Yes, does it works?

**Comment by rayman89** [comment]
Yes if I enable it the addon does not skip intro or goes to next ep.

**Comment by Ceereals** [comment]
Perfect, if you have any suggestion tell me. I close the issue, thank you for the support!

**Comment by rayman89** [comment]
BTW the icon is huge and does this on the customize firefox thing that allows you to arrange icons

![imagen](https://user-images.githubusercontent.com/5449042/34958696-9e730206-f9f8-11e7-97c9-9079ae6c4f7d.png)

**Comment by Ceereals** [comment]
Lol, seriously i don't know why it happened.

**Comment by Ceereals** [comment]
I think it's because of the type of icon. Don't change it lol.

**Comment by rayman89** [comment]
What do you mean?

**Comment by Ceereals** [comment]
I use "svg" as icon type, so i think that the problem come from it. I suggest you, for now, to don't change the size for any trouble.

**Comment by rayman89** [comment]
I did not change anything. I just showed you what happens when you drag and drop the icon to the navigation toolbar.
